### ISSUE TITLE
[REQUEST] Publish JAR

### ISSUE THREAD

**Issue by erasmas** [theoremlp/conjure-openapi#20]
**Context on what is needed**

Hi! As someone who got stuck with Conjure, our team is looking into using conjure-openapi to generate openapi spec. I've realised that it's not easy to use it from Gradle because there's no published Jar artefact or gradle plugin. Would it be possible to publish a Jar in addition to tarball? Thank you!

**Desired end state**

There's a published JAR for conjure-openapi.

**Current work around if any**

We're considering adding tarball contents to our repo but we'd rather not do it. The other alternative is forking `conjure-openapi`, but we'd rather contribute to this repo.

**Proposed implementation**

Publish Jar artefact including for the latest `0.7.0` version.

**Additional context**

n/a

**Comment by mark-thm** [comment]
We do publish an artifact, the readme fails to say as much, though: https://central.sonatype.com/artifact/com.theoremlp.conjure.openapi/conjure-openapi

**Comment by erasmas** [comment]
> We do publish an artifact, the readme fails to say as much, though: https://central.sonatype.com/artifact/com.theoremlp.conjure.openapi/conjure-openapi

Ah, my bad, I failed to see it in `build.gradle`. I wanted to submit a PR with the following change but I couldn't push my branch due to having insufficient permissions.

```
commit aa4d68be508a7a2e3b6b3da1be7c2a59644afb9b
Author: Dmytro Morozov <mail@dmorozov.info>
Date:   Mon Aug 19 17:29:07 2024 +0300

    Update README to mention JAR artefact
    
    https://github.com/theoremlp/conjure-openapi/issues/20

diff --git a/readme.md b/readme.md
index 2cf542b..7bd030d 100644
--- a/readme.md
+++ b/readme.md
@@ -12,6 +12,13 @@ it implements the contract described
         <input>      Path to the input IR file
         <output>     Output directory for generated source
 
+### Using as JAR
+
+The `conjure-openapi` JAR is published to the [Sonatype Maven repository](https://central.sonatype.com/artifact/com.theoremlp.conjure.openapi/conjure-openapi). You can include it in your project by adding the following dependency to your build file:
+
+```groovy
+implementation 'com.theoremlp.conjure.openapi:conjure-openapi'
+
 ## Contributing
 
 To contribute to conjure-openapi:

```

**Comment by erasmas** [comment]
@mark-thm I went to see the artefact on Maven Central Repo and it's there, [but it's a tarball](https://repo1.maven.org/maven2/com/theoremlp/conjure/openapi/conjure-openapi/0.7.0/), not a JAR. This means that it's impossible to include this artefact as a dependency for a gradle task. Would it be possible to publish a regular JAR in addition to tarball?

**Comment by mark-thm** [comment]
@erasmas that's the correct way to distribute a conjure generator -- if you use the gradle-conjure Gradle plugin it'll happily run the conjure -> openapi generation for you.
